apostila/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('add_apostila/', views.add_apostila, name='add_apostila'),
    path('apostila/<int:id>', views.apostila, name='apostila'),
    ]

flashcard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('novo_flashcard/', views.novo_flashcard, name="novo_flashcard"),
    path('delete_flashcard/<int:id>', views.delete_flashcard, name="delete_flashcard"),
    path('iniciar_desafio/', views.iniciar_desafio, name="iniciar_desafio"),
    path('listar_desafio/', views.listar_desafio, name='listar_desafio'),
    path('deletar_desafio/<int:id>', views.deletar_desafio, name="deletar_desafio"),
    path('desafio/<int:id>/', views.desafio, name='desafio'),
    path('responder_flashcard/<int:id>/', views.responder_flashcard, name="responder_flashcard"),
    path('relatorio/<int:id>/', views.relatorio, name='relatorio')
]

lets_study/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda req: redirect('/usuarios/logar')),
    path('usuarios/', include('usuarios.urls')),
    path('flashcard/', include('flashcard.urls')),
    path('apostila/', include('apostila.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe



class Categoria(models.Model):
    nome = models.CharField(max_length=25)

    def __str__(self):
        return self.nome


class Flashcard(models.Model):
    DIFICULDADE_CHOICES = (("D", "Difícil"), ("M", "Médio"), ("F", "Fácil"))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    pergunta = models.CharField(max_length=200)
    resposta = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    dificuldade = models.CharField(max_length=1, choices=DIFICULDADE_CHOICES)

    def __str__(self):
        return self.pergunta

    @property
    def css_dif(self):
        if self.dificuldade == "F":
            return "flashcard-facil"
        elif self.dificuldade == "M":
            return "flashcard-medio"
        elif self.dificuldade == "D":
            return "flashcard-dificil"


class FlashcardDesafio(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.DO_NOTHING)
    respondido = models.BooleanField(default=False)
    acertou = models.BooleanField(default=False)

    def __str__(self):
        return self.flashcard.pergunta


class Desafio(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=100)
    categoria = models.ManyToManyField(Categoria)
    q_perguntas = models.IntegerField()
    dificuldades = models.CharField(max_length=1, choices=Flashcard.DIFICULDADE_CHOICES)
    flashcard = models.ManyToManyField(FlashcardDesafio)

    def __str__(self):
        return self.titulo

    def status(self):
        if self.flashcard.filter(respondido=False).exists():
            return mark_safe('<span class="badge bg-primary">Em aberto</span>')
        else:
            return mark_safe('<span class="badge bg-success">Concluído</span>')

flashcard/views.py
from django.shortcuts import render, redirect

from django.core.exceptions import ObjectDoesNotExist
from .models import Categoria, Flashcard, Desafio, FlashcardDesafio
from django.contrib.messages import constants
from django.contrib import messages
from django.http import HttpResponse, Http404


def novo_flashcard(req):
    if not req.user.is_authenticated:
        return redirect("/usuarios/logar")
    elif req.method == "GET":
        categoria = Categoria.objects.all()
        dificuldades = Flashcard.DIFICULDADE_CHOICES
        flashcards = Flashcard.objects.filter(user=req.user)

        categoria_filter = req.GET.get("categoria")
        dificuldade_filter = req.GET.get("dificuldade")

        if categoria_filter:
            flashcards = flashcards.filter(categoria__id=categoria_filter)

        if dificuldade_filter:
            flashcards = flashcards.filter(dificuldade=dificuldade_filter)

        return render(
            req,
            "novo_flashcard.html",
            {
                "categorias": categoria,
                "dificuldades": dificuldades,
                "flashcards": flashcards,
            },
        )
    elif req.method == "POST":
        pergunta = req.POST.get("pergunta")
        resposta = req.POST.get("resposta")
        categoria = req.POST.get("categoria")
        dificuldade = req.POST.get("dificuldade")

        if len(pergunta.strip()) == 0 or len(resposta.strip()) == 0:
            messages.add_message(
                req, constants.ERROR, "Preencha os campos de pergunta e resposta."
            )
            return redirect("/flashcard/novo_flashcard/")

        flashcard = Flashcard(
            user=req.user,
            pergunta=pergunta,
            resposta=resposta,
            categoria_id=categoria,
            dificuldade=dificuldade,
        )

        flashcard.save()
        messages.add_message(
            req, constants.SUCCESS, "Flashcard cadastrado com sucesso!"
        )
        return redirect("/flashcard/novo_flashcard/")


def delete_flashcard(req, id):
   
    card = Flashcard.objects.get(id=id)
    if not card.user == req.user:
        raise Http404()
    card.delete()
    messages.add_message(req, constants.SUCCESS, "Flashcard apagado com sucesso!")
    return redirect("/flashcard/novo_flashcard/")
       

def iniciar_desafio(req):
    if req.method == "GET":
        categoria = Categoria.objects.all()
        dificuldades = Flashcard.DIFICULDADE_CHOICES
        return render(
            req,
            "iniciar_desafio.html",
            {
                "categorias": categoria,
                "dificuldades": dificuldades,
            },
        )

    elif req.method == "POST":
        titulo = req.POST.get("titulo")
        categorias = req.POST.getlist("categoria")
        dificuldade = req.POST.get("dificuldade")
        q_perguntas = req.POST.get("q_perguntas")

        desafio = Desafio(
            user=req.user,
            titulo=titulo,
            q_perguntas=q_perguntas,
            dificuldades=dificuldade,
        )

        desafio.save()

        for categoria in categorias:
            desafio.categoria.add(categoria)

        flashcards = (
            Flashcard.objects.filter(user=req.user)
            .filter(dificuldade=dificuldade)
            .filter(categoria_id__in=categorias)
            .order_by("?")
        )

        if flashcards.count() < int(q_perguntas):
            return redirect("/flashcard/iniciar_desafio")

        flashcards = flashcards[: int(q_perguntas)]

        for f in flashcards:
            flashcard_desafio = FlashcardDesafio(flashcard=f)
            flashcard_desafio.save()
            desafio.flashcard.add(flashcard_desafio)

        desafio.save()

        return redirect('/flashcard/listar_desafio')


def listar_desafio(req,):  
    desafios = Desafio.objects.filter(user=req.user)
  
    dificuldades = Flashcard.DIFICULDADE_CHOICES
    categorias = Categoria.objects.all()

    categoria = req.GET.get("categoria")
    dificuldade = req.GET.get("dificuldade")

    if categoria:
        desafios = desafios.filter(categoria__id=categoria)

    if dificuldade:
        desafios = desafios.filter(dificuldade=dificuldade)

    return render(
        req,
        "listar_desafio.html",
        {
            "desafios": desafios,
            "categorias": categorias,
            "dificuldades": dificuldades
        },
    )


def deletar_desafio(req, id):
    try:
        desafio = FlashcardDesafio.objects.get(id=id)
        print(desafio)
    except ObjectDoesNotExist:
        messages.add_message(req, constants.ERROR, "Desafio não encontrado!")
        return redirect('/flashcard/listar_desafio')

    if not desafio.user == req.user:
        raise Http404()
    print(desafio)
    desafio.delete()
    messages.add_message(req, constants.SUCCESS, "Desafio apagado com sucesso!")
    return redirect('/flashcard/listar_desafio')

def desafio(req, id):
    
    desafio = Desafio.objects.get(id=id)
    
    if not desafio.user == req.user:
        raise Http404()
    
    if req.method=="GET":
        acertos = desafio.flashcard.filter(respondido=True).filter(acertou=True).count()
        erros = desafio.flashcard.filter(respondido=True).filter(acertou=False).count()
        faltantes = desafio.flashcard.filter(respondido=False).count()
        return render(
            req,
            'desafio.html',
            {
                'desafio': desafio,
                'acertos': acertos,
                'erros': erros,
                'faltantes': faltantes
            }
        )


def responder_flashcard(req, id):
    flashcard_desafio = FlashcardDesafio.objects.get(id=id)
    acertou = req.GET.get('acertou')
    flashcard_desafio.respondido = True
    desafio_id = req.GET.get('desafio_id')
    '''
    if basico
    if acertou == "1":
        flashcard_desafio.acertou = True
    elif acertou == "0":
        flashcard_desafio.acertou = False'''
        
    #if avancado
    
    if not flashcard_desafio.flashcard.user == req.user:
        raise Http404
    
    flashcard_desafio.acertou = True if acertou == "1" else False
    flashcard_desafio.save()
    return redirect(f"/flashcard/desafio/{desafio_id}")


def relatorio(req, id):
    desafio = Desafio.objects.get(id=id)
    acertos = desafio.flashcard.filter(acertou=True).count()
    erros = desafio.flashcard.filter(acertou=False).count()
    dados = [acertos, erros]
    
    
    categorias = desafio.categoria.all()
    labels = []
    for i in categorias:
        labels.append(i.nome)
        
    dados2 = []
    for categoria in categorias:
        dados2.append(desafio.flashcard.filter(flashcard__categoria=categoria).filter(acertou=True).count())
        
    
    return render(req, 'relatorio.html', {'desafio': desafio, 'dados': dados, 'labels': labels, 'dados2': dados2})

flashcard/templates/desafio.html
{% extends "base.html" %} {% load static %} {% block 'header' %}
<link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet" />
<link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet" />
<link
  href="{% static 'flashcard/css/iniciar_desafio.css' %}"
  rel="stylesheet"
/>
<link href="{% static 'flashcard/css/desafio.css' %}" rel="stylesheet" />
<link
  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
  rel="stylesheet"
/>
{% endblock 'header' %} {% block 'conteudo' %} 
{% include "partials/header.html" %}
<div class="container">
  <br />
  <br />
  <div class="row">
    <div class="col-md">
      <h3 class="fonte-secundaria">Desafio iniciado:</h3>
      <hr />
      {% for cat in desafio.flashcard.flashcard %}
        <div>{{cat.categoria}}</div>
      {% endfor %}
      <br />
      <br />
      <br />
      {% for flash in desafio.flashcard.all %}
      <div class="box-new-flashcard {% if flash.respondido %} op2 {% endif %}">
        <div class="flashcard {{flash.flashcard.css_dif}}">
          <div class="flashcard-categoria">{{flash.flashcard.categoria}}</div>
          <br />
          <br />
          <div class="flashcard-box-item" onclick="flip_card({{flash.id}})">
            <p class="flashcard-item">{{flash.flashcard.pergunta}}</p>
          </div>

          {% if not flash.respondido %}
          <div class="responder">
            <a
              href="{% url 'responder_flashcard' flash.id %}?acertou=0&desafio_id={{desafio.id}}"
              ><i class="bx bxs-x-square icone-vermelho"></i
            ></a>
            <a
              href="{% url 'responder_flashcard' flash.id %}?acertou=1&desafio_id={{desafio.id}}"
              ><i class="bx bxs-check-square icone-verde"></i
            ></a>
          </div>
          {% else %} {% if flash.acertou %}
          <span class="badge bg-success">Acertou</span>
          {% else %}
          <span class="badge bg-danger">Errou</span>
          {% endif %} {% endif %}
        </div>
        <div class="resposta-flashcard" id="{{flash.id}}">
          {{flash.flashcard.resposta}}
        </div>
      </div>
      <br />
      <br />
      {% endfor %}
    </div>
    <div class="col-md">
      <div class="box-res">
        <h3 class="fonte-secundaria">Resultado:</h3>
        <p class="fonte-p">Acertos: {{acertos}}</p>
        <p class="fonte-p">Erros: {{erros}}</p>
        <p class="fonte-p">Faltantes: {{faltantes}}</p>
      </div>
      <br />
      <a class="btn-cadastro btn-desafio" href="{% url 'relatorio' desafio.id %}">Relatório detalhado</a>
    </div>
  </div>
</div>
<script src="{% static 'flashcard/js/index.js' %}"></script>
{% endblock 'conteudo' %}

flashcard/templates/iniciar_desafio.html
{% extends "base.html" %}
{% load static %}
{% block 'header' %}
 <link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet">
 <link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet">
 <link href="{% static 'flashcard/css/iniciar_desafio.css' %}" rel="stylesheet">
{% endblock 'header' %}
{% block 'conteudo' %}
{% include "partials/header.html" %}
    <div class="container ctx">
    <br>
    <br>
    <h2 class="fonte-principal">Iniciar desafio</h2>
    <p class="fonte-secundaria">Escolha as categorias e a dificuldade do desafio</p>
    <div class="row">
 
        <div class="col-md">
            <form action="{% url 'iniciar_desafio' %}" method="POST">{% csrf_token%}
            <label for="">Titulo</label>
            <input type="text" class="form-control " name="titulo" required autocomplete="off">
        </div>
        <div class="col-md">
            <label>Categoria:</label>
            <select name="categoria" class="form-select" multiple required>
                {% for categoria in categorias %}
                    <option value="{{categoria.id}}">
                        {{categoria.nome}}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md">
            <label>Dificuldade:</label>
            <select name="dificuldade" class="form-select" required>
                {% for dificuldade in dificuldades %}
                    <option value="{{dificuldade.0}}">
                        {{dificuldade.1}}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="col-md">
            <label>Quantas questões:</label>
            <input type="number" class="form-control" required name="q_perguntas" autocomplete="off">
        </div>
 
    </div>
    <br>
    <br>
    <input type="submit" class="btn-cadastro" value="Iniciar desafio">
 </form>
 </div>
{% endblock 'conteudo' %}

flashcard/templates/listar_desafio.html
{% extends "base.html" %}
{% load static %}
{% block 'header' %}
 <link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet">
 <link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet">
 <link href="{% static 'flashcard/css/iniciar_desafio.css' %}" rel="stylesheet">
 <link href="{% static 'flashcard/css/desafio.css' %}" rel="stylesheet">
 <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% endblock 'header' %}
{% block 'conteudo' %}
{% include "partials/header.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <form action="" method="GET">
                <label for="">Categoria</label>
                <select name="categoria" class="form-select">
                    <option value="">Todas as categorias:</option>
                    {% for categoria in categorias %}
                        <option value="{{categoria.id}}">{{categoria}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <label for="">Dificuldade</label>
                <select name="dificuldade" class="form-select">
                    <option value="">Todas as dificuldades:</option>
                    {% for dificuldade in dificuldades %}
                        <option value="{{dificuldade.0}}">{{dificuldade.1}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <br>
                <input type="submit" value="Filtrar" class="btn-cadastro">
                </form>
            </div>

        </div>
        <br>
        <br>
        <div class="box-listar">
            {% if messages %}
            <br />
            {% for message in messages %}
                <section class="alert {{message.tags}}">{{message}}</section>
            {% endfor %} {% endif %}
            <table>
                <thead>
                    <tr class="header" >
                        <th scope="col">Desafio</th>
                        <th scope="col">Titulo</th>
                        <th scope="col">Dificuldade</th>
                        <th scope="col">Status</th>
                        
                    </tr>
                </thead>
                
                <tbody>
                    {% for desafio in desafios %}
                        <tr class="linha">
                            <th><a href="{% url 'desafio' desafio.id %}">{{desafio.id}}</a></th>
                            <td>{{desafio.titulo}}</td>
                            <td>{{desafio.get_dificuldades_display}}</td>
                            <td>{{desafio.status}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script src="{% static 'flashcard/js/flashcard.js' %}"></script>
{% endblock 'conteudo' %}

flashcard/templates/novo_flashcard.html
{% extends "base.html" %} {% load static %} {% block 'header' %}
<link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet" />
<link
  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
  rel="stylesheet"
/>
<link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet" />
{% endblock 'header' %} {% block 'conteudo' %} {% include "partials/header.html" %}
<div class="container">
  <br />
  <br />
  <div class="row">
    <div class="col-md">
      <div class="box-form">
        <form action="{% url 'novo_flashcard' %}" method="POST">
          {% csrf_token %}
          <h3>Novo flashcard</h3>
          {% if messages %}
          <br />
          {% for message in messages %}
          <section class="alert {{message.tags}}">{{message}}</section>
          {% endfor %} {% endif %}
          <br />
          <label>Pergunta:</label>
          <input type="text" class="form-control" name="pergunta" required autocomplete="off" />
          <br />
          <label>Resposta:</label>
          <textarea
            class="form-control"
            name="resposta"
            rows="6"
            required
            autocomplete="off"
          ></textarea>
          <br />
          <div class="row">
            <div class="col-md">
              <label for="">Categoria:</label>
              <select class="form-select" name="categoria">
                {% for categoria in categorias %}
                <option value="{{categoria.id}}">{{categoria}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-md">
              <label for="">Dificuldade:</label>
              <select class="form-select" name="dificuldade">
                {% for dificuldade in dificuldades %}
                <option value="{{dificuldade.0}}">{{dificuldade.1}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <br />
          <input type="submit" value="Enviar" class="btn-cadastro" />
          <br />
          <br />
          <br />
        </form>
      </div>
    </div>
    <div class="col-md">
      <form action="{% url 'novo_flashcard' %}" method="GET">
        {% csrf_token %}
        <div class="row">
          <div class="col-md">
            <label for="">Categoria:</label>
            <select name="categoria" id="" class="form-select">
              <option value="">Todas as categorias:</option>
              {% for categoria in categorias %}
              <option value="{{categoria.id}}">{{categoria}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md">
            <label for="">Dificuldade:</label>
            <select name="dificuldade" id="" class="form-select">
              <option value="">Todas as dificuldades:</option>
              {% for dificuldade in dificuldades %}
              <option value="{{dificuldade.0}}">{{dificuldade.1}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md">
            <br />
            <input
              type="submit"
              style="width: 100%"
              value="Filtrar"
              class="btn-cadastro"
            />
          </div>
        </div>
      </form>
      <br />
      <br />

      {% for flash in flashcards %}
      <div class="box-new-flashcard">
        <div class="flashcard {{flash.css_dif}}">
          <div class="flashcard-categoria">{{flash.categoria}}</div>
          <a href="{% url 'delete_flashcard' flash.id %}"
            ><i class="icone-exit bx bx-x-circle"></i
          ></a>
          <br />
          <div class="flashcard-box-item" onClick="flip_card({{flash.id}})">
            <p class="flashcard-item">{{flash.pergunta}}</p>
          </div>
        </div>

        <div class="resposta-flashcard" id="{{flash.id}}">
          Resposta: {{flash.resposta}}
        </div>
      </div>
      <br />
      <br />
      {% endfor %}
    </div>
  </div>
</div>

<script src="{% static 'flashcard/js/index.js' %}"></script>
{% endblock 'conteudo' %}

flashcard/templates/relatorio.html
{% extends "base.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'usuarios/css/cadastro.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/novo_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/iniciar_desafio.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/desafio.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'conteudo' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <p class="fonte-secundaria">{{desafio.titulo}}</p>
                <hr>
                <canvas id="grafico1"></canvas>
            </div>
            <div class="col-md">
                <br><br><br><br>
              
                <div style="background-color: white;">

                    <canvas id="grafico2"></canvas>

                </div>
            </div>
        </div>
      
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    <script>
        const ctx = document.getElementById('grafico1');
      
        new Chart(ctx, {
          type: 'pie',
          data: {
            labels: ['Acertos', 'Erros'],
            datasets: [{
              label: 'Qtd',
              data: {{dados}},
              borderWidth: 1
            }]
          },
          
        });
    </script>

    <script>

        const ctx2 = document.getElementById('grafico2');
      
        new Chart(ctx2, {
          type: 'radar',
          data: {
            labels: {{labels | safe}},
            datasets: [{
              label: 'Qtd',
              data: {{dados2}},
              borderWidth: 1,
              fill: true,
              
            }]
          },
          
        });

    </script>

{% endblock 'conteudo' %}